### ISSUE TITLE
Glyph Source: Reconcile Weight Values

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Assistant#1]
Hi @cjdunn,

Could you look at glyphs source file of **Assistant** and reconcile any weight values between the masters and instances.  The outlines are sometimes extrapolated so need to pair up the styles between the two in terms of visual weight and look at the outlines displayed in the font info. Thanks!

**Comment by cjdunn** [comment]
I've updated this and pushed changes here:
https://github.com/TypeNetwork/Assistant/tree/fea-ufo-conv
