### ISSUE TITLE
Add Glyphs

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/Assistant#2]
@victoriaalissia 

Add these glyphs to the two masters
Assistant-ExtraLight.ufo
Assistant-ExtraBold.ufo

* 🔥 **FAIL** Missing required codepoints: 0x000D (CARRIAGE RETURN), 0x00B2 (SUPERSCRIPT TWO), 0x00B3 (SUPERSCRIPT THREE), 0x00B5 (MICRO SIGN), 0x00B9 (SUPERSCRIPT ONE) and 0x2074 (SUPERSCRIPT FOUR) [code: missing-codepoints]

**Comment by victoriaalissia** [comment]
Done and synced
