### ISSUE TITLE
Vertical metrics

### ISSUE THREAD

**Issue by djrrb** [TypeNetwork/Assistant#6]
🔥 FAIL OS/2.usWinAscent value should be equal or greater than 1021, but got 950 instead [code: ascent]

🔥 FAIL OS/2 sTypoAscender (750) and hhea ascent (950) must be equal. [code: ascender]

**Comment by djrrb** [comment]
use hhea value as source, set useTypoMetrics

**Comment by moyogo** [comment]
To set the useTypoMetrics, see https://github.com/TypeNetwork/Cinzel/commit/9f7ba17 which enables the bit 7 in font.info.openTypeOS2Selection:
```xml
    <key>openTypeOS2Selection</key>
    <array>
      <integer>7</integer>
    </array>
```

**Comment by djrrb** [comment]
Ah nice! Thank you. I added the following to the build script, which I think accomplishes the same thing?

```gftools fix-fsselection $ttf --usetypometrics;```

**Comment by moyogo** [comment]
Yes, indeed!
